import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { useEffect, useRef } from "react";
import { aseEncode, sortColors, timestamp } from "@/localLib/util";
import Link from "next/link";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>1.COLOR</h1>
        <h3></h3>
        <ul>
          <li>
            <Link href="/1_color/p1_2_2_01">画像で作るカラーパレット</Link>
          </li>
        </ul>

        {/* <Link href="/installConsidation/">導入・実装方法のパターン</Link> */}
        <cancas id="canvas"></cancas>
      </main>
    </>
  );
}
