import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { useEffect, useRef } from "react";
import { aseEncode, sortColors, timestamp } from "@/localLib/util";
const tileCountX = 50;
const tileCountY = 10;
const hueValues = [];
const brightnessValues = [];
const saturationValues = [];
export default function Home() {
  const img = useRef(null);
  const colors = useRef([]);
  const sortMode = useRef(null);

  useEffect(() => {
    const p5 = require("p5");

    new p5((p) => {
      p.preload = () => {
        img.current = p.loadImage("/1_generativeDesign/sample.jpg");
      };
      p.setup = () => {
        p.createCanvas(window.innerWidth - 100, window.innerHeight - 100);
        p.colorMode(p.HSB, 360, 100, 100, 100);
        p.noStroke();
        for (let i = 0; i < tileCountX; i++) {
          hueValues[i] = p.random(360);
          saturationValues[i] = p.random(100);
          brightnessValues[i] = p.random(100);
        }
      };
      p.draw = () => {
        p.background(0, 0, 100);
        let mX = p.constrain(p.mouseX, 0, p.width);
        let mY = p.constrain(p.mouseY, 0, p.height);

        let counter = 0;

        let currentTileCountX = p.int(p.map(mX, 0, p.width, 1, tileCountX));
        let currentTileCountY = p.int(p.map(mY, 0, p.height, 1, tileCountY));
        let tileWidth = p.width / currentTileCountX;
        let tileHeight = p.height / currentTileCountY;

        for (let gridY = 0; gridY < tileCountY; gridY++) {
          for (let gridX = 0; gridX < tileCountX; gridX++) {
            let posX = tileWidth * gridX;
            let posY = tileHeight * gridY;
            let index = counter % currentTileCountX;
            // let col = p.color(
            //   hueValues[index],
            //   saturationValues[index],
            //   brightnessValues[index]
            // );
            p.fill(col);
            p.rect(posX, posY, tileWidth, tileHeight);
            counter++;
          }
        }
      };

      p.keyReleased = () => {
        if (p.key == "c" || p.key == "C")
          p.writeFile([aseEncode(colors.current)], timestamp(), "ase");
        if (p.key == "s" || p.key == "S") p.saveCanvas(timestamp(), "png");

        if (p.key == "0") p.loadImage("/1_generativeDesign/picSakamoto2.jpg", setImage);
        if (p.key == "1") p.loadImage("/1_generativeDesign/pic1.jpg", setImage);
        if (p.key == "2") p.loadImage("/1_generativeDesign/pic2.jpg", setImage);
        if (p.key == "3") p.loadImage("/1_generativeDesign/pic3.jpg", setImage);
        if (p.key == "4") p.loadImage("/1_generativeDesign/pic4.jpg", setImage);

        if (p.key == "5") sortMode.current = null;
        if (p.key == "6") sortMode.current = "hue";
        if (p.key == "7") sortMode.current = "saturation";
        if (p.key == "8") sortMode.current = "brightness";
        if (p.key == "9") sortMode.current = "grayscale";
      };

      function setImage(loadedImageFile) {
        img.current = loadedImageFile;
      }
    }, "#canvas");
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>画像で作るカラーパレット</h3>
        {/* <Link href="/installConsidation/">導入・実装方法のパターン</Link> */}
        <cancas id="canvas"></cancas>
      </main>
    </>
  );
}
