import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { useEffect, useRef } from "react";
import { timestamp } from "@/localLib/util";
export default function Home() {
  useEffect(() => {
    const p5 = require("p5");
    new p5((p) => {
      p.setup = () => {
        p.createCanvas(550, 550);
        p.strokeCap(p.SQUARE);
      };
      p.draw = () => {
        p.background(255);
        p.translate(p.width / 2, p.height / 2);
        let circleResolution = p.int(p.map(p.mouseY, 0, p.height, 2, 80));
        let radius = p.mouseX - p.width / 2;
        let angle = p.TAU / circleResolution;

        const aaa = p.map(20, 0, 1920, 0, 255);
        console.log(aaa);

        p.strokeWeight(p.mouseY / 20);

        for (let i = 0; i <= circleResolution; i++) {
          let x = p.cos(angle * i) * radius;
          let y = p.sin(angle * i) * radius;
          p.line(0, 0, x, y);
        }
      };

      p.keyReleased = () => {
        if (p.key === "s" || p.key === "S") p.savaCanvas(timestamp(), "png");
      };
    }, "#canvas");
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>random rect, random color</h3>
        <cancas id="canvas"></cancas>
      </main>
    </>
  );
}
