import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";

export default function Home() {
  return (
    <>
      <Head>
        <title>導入方法1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://cdn.jsdelivr.net/npm/p5@1.9.1/lib/p5.js"></Script>
      <Script src="/installConsidation/IC1_moduled.js"></Script>
      <main id="content" className={styles.main}>
        <p>普通にscriptタグでライブラリを読み込みスクリプトを呼び出す</p>
      </main>
    </>
  );
}
