import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
// import * as p5 from "p5";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    const p5 = require("p5");
    new p5((p) => {
      p.setup = () => {
        p.createCanvas(400, 400);
        p.background(0);
      };
      p.draw = () => {
        p.background(0);
        p.ellipse(p.mouseX, p.mouseY, 40, 40);
      };
    }, "canvas");
  }, []);
  return (
    <>
      <Head>
        <title>導入方法2:require</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="content" className={styles.main}></main>
    </>
  );
}
