import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>p5.js</h1>
        <h3>始める前に</h3>
        <Link href="/installConsidation/">導入・実装方法のパターン</Link>
        <h3>1.color</h3>
        <ul>
          <li>
            <a href="/1_color/p1_2_2_01">画像で作るカラーパレット(p1_2_2_01)</a>
          </li>
          <li>
            <a href="/1_color/p1_2_3_01">ルールで作るカラーパレット(p1_2_3_01)</a>
          </li>
          <li>
            <a href="/1_color/p1_2_3_02">p1_2_3_02</a>
          </li>
        </ul>
        <h3>2.image</h3>
        <ul>
          <li>
            <a href="/2_image">image</a>
          </li>
        </ul>
      </main>
    </>
  );
}
