import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { useEffect } from "react";
import { timestamp } from "@/localLib/util";
export default function Home() {
  useEffect(() => {
    const p5 = require("p5");
    let moduleColor;
    let moduleAlpha = 180;
    let maxDistance = 500;
    new p5((p) => {
      p.setup = () => {
        p.createCanvas(600, 600);
        p.noFill();
        p.strokeWeight(3);
        moduleColor = p.color(0, 0, 0, moduleAlpha);
      };
      p.draw = () => {
        p.clear();
        p.stroke(moduleColor);
        for (let gridY = 0; gridY < p.width; gridY += 25) {
          for (let gridX = 0; gridX < p.height; gridX += 25) {
            let diameter = p.dist(p.mouseX, p.mouseY, gridX, gridY);
            diameter = (diameter / maxDistance) * 40;
            p.push();
            p.translate(gridX, gridY, diameter * 5);
            p.rect(0, 0, diameter, diameter);
            p.pop();
          }
        }
      };
      p.keyReleased = () => {
        if (p.key === "s" || p.key === "S") p.saveCanvas(timestamp(), "png");
      };
    }, "#canvas");
  }, []);

  return (
    <>
      <Head>
        <title>グリッドと動き3(p2_1_2_03)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>グリッドと動き3(p2_1_2_03)</h3>
        <div>s:save png</div>
        <cancas id="canvas"></cancas>
      </main>
    </>
  );
}
