import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { useEffect } from "react";
import { timestamp } from "@/localLib/util";
import { random } from "chroma-js";
export default function Home() {
  useEffect(() => {
    const p5 = require("p5");
    let tileCount = 20;
    let actRandomSeed = 0;
    let rectSize = 30;
    new p5((p) => {
      p.setup = () => {
        p.createCanvas(600, 600);
        p.colorMode(p.HSB, 360, 100, 100, 100);
        // p.noLoop();
        p.noStroke();
        p.fill(192, 100, 64, 60);
      };
      p.draw = () => {
        p.clear();
        p.randomSeed(actRandomSeed);
        for (let gridY = 0; gridY < tileCount; gridY++) {
          for (let gridX = 0; gridX < tileCount; gridX++) {
            let posX = (p.width / tileCount) * gridX;
            let posY = (p.height / tileCount) * gridY;
            const diff = 0.05;
            let shiftX1 = (p.mouseX / 20) * p.random(-diff, diff);
            let shiftY1 = (p.mouseY / 20) * p.random(-diff, diff);
            let shiftX2 = (p.mouseX / 20) * p.random(-diff, diff);
            let shiftY2 = (p.mouseY / 20) * p.random(-diff, diff);
            let shiftX3 = (p.mouseX / 20) * p.random(-diff, diff);
            let shiftY3 = (p.mouseY / 20) * p.random(-diff, diff);
            let shiftX4 = (p.mouseX / 20) * p.random(-diff, diff);
            let shiftY4 = (p.mouseY / 20) * p.random(-diff, diff);
            p.push();
            p.translate(posX, posY);
            p.beginShape();
            p.vertex(shiftX1, shiftY1);
            p.vertex(rectSize + shiftX2, shiftY2);
            p.vertex(rectSize + shiftX3, rectSize + shiftY3);
            p.vertex(shiftX4, rectSize + shiftY4);
            p.endShape();
            p.pop();
          }
        }
      };
      p.mousePressed = () => {
        actRandomSeed = random(100000);
      };
      p.keyReleased = () => {
        if (p.key == "s" || p.key == "S") p.saveCanvas(timestamp(), "png");
      };
    }, "#canvas");
  }, []);

  return (
    <>
      <Head>
        <title>グリッドと動き4(p2_1_2_04)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>グリッドと動き4(p2_1_2_04)</h3>
        <div>s:save png</div>
        <cancas id="canvas"></cancas>
      </main>
    </>
  );
}
