import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { useEffect } from "react";
import { timestamp } from "@/localLib/util";
export default function Home() {
  useEffect(() => {
    const p5 = require("p5");

    var tileCount = 20;
    var actRandomSeed = 0;
    let actStrokeCap;
    new p5((p) => {
      p.setup = () => {
        p.createCanvas(600, 600);
        actStrokeCap = p.ROUND;
      };
      p.draw = () => {
        p.clear();
        p.strokeCap(actStrokeCap);
        p.randomSeed(actRandomSeed);

        for (let gridY = 0; gridY < tileCount; gridY++) {
          for (let gridX = 0; gridX < tileCount; gridX++) {
            let posX = (p.width / tileCount) * gridX;
            let posY = (p.height / tileCount) * gridY;
            let toggle = p.int(p.random(0, 2));
            if (toggle === 0) {
              p.strokeWeight(p.mouseX / 20);
              p.line(posX, posY, posX + p.width / tileCount, posY + p.height / tileCount);
            }
            if (toggle === 1) {
              p.strokeWeight(p.mouseY / 20);
              p.stroke(0);
              p.line(posX, posY + p.width / tileCount, posX + p.height / tileCount, posY);
            }
          }
        }
      };
      p.mousePressed = () => {
        actRandomSeed = p.random(100000);
      };
      p.keyReleased = () => {
        if (p.key == "s" || p.key == "S") p.saveCanvas(timestamp(), "png");
        if (p.key == "1") actStrokeCap = p.ROUND;
        if (p.key == "2") actStrokeCap = p.SQUARE;
        if (p.key == "3") actStrokeCap = p.PROJECT;
      };
    }, "#canvas");
  }, []);

  return (
    <>
      <Head>
        <title>グリッドと整列(p2_1_1_01)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>グリッドと整列(p2_1_1_01)</h3>
        <div>key1:Round, key2:SQUARE, key3:PROJECT, s:sava png</div>
        <cancas id="canvas"></cancas>
      </main>
    </>
  );
}
